---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 7dc22543ff22a15ce8d2bc5fcd58867003885916
    fabric8.io/git-branch: 7dc22543ff22a15ce8d2bc5fcd58867003885916
    fabric8.io/git-url: https://github.com/chungsju/Provider_CICD.git
  labels:
    container: provider
    provider: fabric8
    project: provider
    group: com.tibco.bw
    expose: "true"
    app: Provider.application
    version: 1.0.0-SNAPSHOT
  name: provider-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    container: provider
    provider: fabric8
    project: provider
    group: com.tibco.bw
    app: Provider.application
  type: NodePort
