apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  managedFields:
  - apiVersion: autoscaling/v1
  name: consumer
  namespace: default
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  targetCPUUtilizationPercentage: 50
