---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: d7ca3808602a0826a879907598a20cb30156452b
    fabric8.io/git-branch: d7ca3808602a0826a879907598a20cb30156452b
    fabric8.io/git-url: https://github.com/chungsju/Consumer_CICD.git
  labels:
    container: consumer
    provider: fabric8
    project: consumer
    group: com.tibco.bw
    app: Consumer.application
    version: 1.0.0
  name: consume-svc
  namespace: default
spec:
  ports:
  - nodePort: 32170
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    container: consumer
    provider: fabric8
    project: consumer
    group: com.tibco.bw
    app: Consumer.application
  type: NodePort
