---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: Consumer.application
    provider: fabric8
    version: 1.0.0
    group: com.tibco.bw
  name: default
  namespace: default
status:
  phase: Active
