---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 0b8e712df5ea77cc83fd86719d18d458fa86846b
    fabric8.io/git-branch: 0b8e712df5ea77cc83fd86719d18d458fa86846b
    fabric8.io/git-url: https://github.com/chungsju/Provider_CICD.git
  labels:
    container: provider
    provider: fabric8
    project: provider
    group: com.tibco.bw
    app: Provider.application
    version: 1.8.0
  name: provider-svc
  namespace: default
spec:
  ports:
  - nodePort: 32180
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    container: provider
    provider: fabric8
    project: provider
    group: com.tibco.bw
    app: Provider.application
  type: NodePort
