---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 751322282d30c8adfcc9050bf51aaad0c0480169
    fabric8.io/git-branch: 751322282d30c8adfcc9050bf51aaad0c0480169
    fabric8.io/git-url: https://github.com/chungsju/Provider_CICD.git
  labels:
    app: Provider.application
    provider: fabric8
    version: 1.7.0
    group: com.tibco.bw
  name: provider
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: Provider.application
      provider: fabric8
      group: com.tibco.bw
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 751322282d30c8adfcc9050bf51aaad0c0480169
        fabric8.io/git-branch: 751322282d30c8adfcc9050bf51aaad0c0480169
        fabric8.io/git-url: https://github.com/chungsju/Provider_CICD.git
      labels:
        container: provider
        project: provider
        app: Provider.application
        provider: fabric8
        version: 1.7.0
        group: com.tibco.bw
      name: provider
      namespace: default
    spec:
      containers:
      - env:
        - name: PROVIDER_PORT
          value: "8000"
        - name: APP_CONFIG_PROFILE
          value: docker
        - name: BW_PROFILE
          value: Docker
        image: chungsju/provider:1.7.0
        imagePullPolicy: Always
        name: provider
        ports:
        - containerPort: 8000
          name: irdmi
        readinessProbe:
          httpGet:
            path: /provider
            port: 8000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
