---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 57092de897eb90110f9378d2ba2ab3aaee35a78c
    fabric8.io/git-branch: 57092de897eb90110f9378d2ba2ab3aaee35a78c
    fabric8.io/git-url: https://github.com/chungsju/Provider_CICD.git
  labels:
    app: Provider.application
    provider: fabric8
    version: 1.7.0
    group: com.tibco.bw
  name: provider
  namespace: default
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: Provider.application
      provider: fabric8
      group: com.tibco.bw
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 57092de897eb90110f9378d2ba2ab3aaee35a78c
        fabric8.io/git-branch: 57092de897eb90110f9378d2ba2ab3aaee35a78c
        fabric8.io/git-url: https://github.com/chungsju/Provider_CICD.git
      labels:
        container: provider
        project: provider
        app: Provider.application
        provider: fabric8
        version: 1.7.0
        group: com.tibco.bw
      name: provider
      namespace: default
    spec:
      containers:
      - env:
        - name: PROVIDER_PORT
          value: "8000"
        - name: APP_CONFIG_PROFILE
          value: docker
        - name: BW_PROFILE
          value: Docker
        image: chungsju/provider:1.7.0
        imagePullPolicy: Always
        name: provider
        ports:
        - containerPort: 8000
          name: irdmi
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 200m
