---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 5051addc111ab5e680cdf653fbec41caad014b47
    fabric8.io/git-branch: 5051addc111ab5e680cdf653fbec41caad014b47
    fabric8.io/git-url: https://github.com/chungsju/Provider_CICD.git
  labels:
    app: Provider.application
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: com.tibco.bw
  name: provider
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: Provider.application
      provider: fabric8
      group: com.tibco.bw
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 5051addc111ab5e680cdf653fbec41caad014b47
        fabric8.io/git-branch: 5051addc111ab5e680cdf653fbec41caad014b47
        fabric8.io/git-url: https://github.com/chungsju/Provider_CICD.git
      labels:
        container: provider
        project: provider
        app: Provider.application
        provider: fabric8
        version: 1.0.0-SNAPSHOT
        group: com.tibco.bw
      name: provider
      namespace: default
    spec:
      containers:
      - env:
        - name: BW_APP_MONITORING_CONFIG
          value: '{"url":"http://bwce-mon-svc:8080"}'
        - name: PROVIDER_PORT
          value: "8000"
        - name: APP_CONFIG_PROFILE
          value: docker
        - name: BW_PROFILE
          value: Docker
        image: chungsju/provider:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        name: provider
        ports:
        - containerPort: 8000
          name: irdmi
