pipeline {
    agent any
    tools {
        // Jenkins 환경설정에서 자동으로 설치한 Maven의 Name
        maven "Maven3"
    }
	stages {
        stage('SCM Check out test') {
            steps {
               sh "ls -al"
            }
        }
        stage('Change Directory') {
            steps {
               sh "cd Provider.application.parent"
            }
        }
        stage('SCM Check out test2') {
            steps {
               sh "ls -al"
            }
        }
        stage('Clean & Package') {
            steps {
                 sh "mvn clean package"
            }
        }
        stage('Docker Image Build') {
            steps {
                 sh "mvn package initialize docker:build"
            }
        }
        stage('Docker Image push') {
            steps {
                 // setting.xml 환경설정파일 참조 
                 sh "mvn initialize docker:push -s Provider.application.parent/setting.xml"
            }
        }
        stage('Kubernetes Resource') {
            steps {
                 sh "mvn initialize com.tibco.plugins:bw6-maven-plugin:bwfabric8json fabric8:resource"
            }
        }
        stage('Kubernetes Apply') {
            steps {
                 sh "mvn  initialize fabric8:apply"
            }
        }
    }
}
