pipeline {
    agent any
    tools {
        // Jenkins 환경설정에서 자동으로 설치한 Maven의 Name
        maven "Maven3"
    }
	stages {
        stage('SCM Check out test') {
            steps {
               sh "ls -al"
            }
        }
        stage('Clean & Package') {
            steps {
                dir("Provider.application.parent") {
               		 sh "mvn clean package"
               	}
            }
        }
        stage('Docker Image Build') {
            steps {
            	 dir("Provider.application.parent") {
               		 sh "mvn package initialize docker:build"
               	}
            }
        }
        stage('Docker Image push') {
            steps {
                 dir("Provider.application.parent") {
               		// setting.xml 환경설정파일 참조 
                 	sh "mvn initialize docker:push -s setting.xml"
               	}
            }
        }
        stage('Kubernetes Resource') {
            steps {
                 dir("Provider.application.parent") { 
                 	sh "mvn initialize com.tibco.plugins:bw6-maven-plugin:bwfabric8json fabric8:resource"
               	} 
            }
        }
        stage('Kubernetes Apply') {
            steps {
                  dir("Provider.application.parent") {
                 	   sh "mvn  initialize fabric8:apply"
               	}
             
            }
        }
    }
}
